import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
  /** "Bloquear contato" (migration 037). Optional — absent on payloads
   *  fetched before this column existed. */
  is_blocked?: boolean;
  blocked_at?: string;
  blocked_by_user_id?: string;
  /** "Group-as-synthetic-contact" (migration 049) — true means this row
   *  represents a WhatsApp GROUP, not a person. `phone` holds `group_jid`
   *  too (never a real dialable number) so nothing crashes on a NULL
   *  phone; any phone-SEND code path must check this flag first and use
   *  `group_jid` as the actual send target for Evolution API instead. */
  is_group_placeholder?: boolean;
  /** WhatsApp group JID, e.g. '120363123456789012@g.us'. Only set when
   *  is_group_placeholder is true. */
  group_jid?: string;
  /** Whether `name` is still auto-synced from WhatsApp (pushName /
   *  profile lookup) or was frozen by an explicit manual edit — see
   *  migration 050. Defaults to 'whatsapp' for existing rows. */
  name_source?: 'whatsapp' | 'manual';
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
  /** True for "Notas internas" (migration 039); false/absent = the
   *  Inbox sidebar's general Notes feed. */
  is_internal?: boolean;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * Conversation-list context-menu state (migration 037): pin floats
   * the conversation to the top of the list; favorite/archive/mute are
   * plain flags toggled from the right-click menu / sidebar.
   */
  is_pinned: boolean;
  is_favorite: boolean;
  is_archived: boolean;
  is_muted: boolean;
  /** True for a WhatsApp group conversation. Added as groundwork in
   *  migration 044 (still always false for Meta Cloud API conversations,
   *  which can't ingest group chats at all), then actually populated once
   *  Evolution API group support shipped (migration 049) — set by
   *  `markConversationAsGroup` in evolution-ingest.ts, both on first
   *  ingest and during history sync. `group_participant_count` is written
   *  by that same function. */
  is_group: boolean;
  group_participant_count?: number;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
  /** Manual drag-to-reorder position within whatever Kanban column this
   *  conversation is currently in (migration 056) — independent of
   *  which column that is. Fractional/gap-based; null for a row that's
   *  never been manually reordered (falls back to last_message_at). */
  kanban_position?: number | null;
  /** Inbox Kanban bucket (migration 057) — decoupled from `deals`, see
   *  `BoardColumn`. Nullable by design (never enforced NOT NULL, to
   *  avoid a migration/deploy-order race); the bucketing memo in
   *  inbox/page.tsx falls back to the account's default-for-leads
   *  column when this is null. */
  board_column_id?: string | null;
  /** Denormalized, trigger-maintained (migration 057) — timestamp of
   *  the most recent message in each direction, used by the "Última
   *  mensagem enviada/recebida" board-column sort modes. */
  last_inbound_message_at?: string | null;
  last_outbound_message_at?: string | null;
}

// ============================================================
// Inbox Kanban board columns (migration 057)
//
// Freely editable/reorderable buckets a conversation can be placed
// in, independent of `pipelines`/`deals` — see the "Pivot" section of
// the roadmap plan for why. Exactly one column per account is always
// flagged is_default_for_leads and one is_default_for_groups (partial
// unique indexes in the migration); new conversations are filed into
// whichever applies at creation time (assign-default-board-column.ts).
// ============================================================

export type BoardColumnSortMode =
  | "last_message_at"
  | "last_outbound_message_at"
  | "last_inbound_message_at"
  | "next_reminder_any"
  | "next_reminder_manual"
  | "next_reminder_automated"
  | "manual";

export interface BoardColumn {
  id: string;
  account_id: string;
  name: string;
  color: string;
  position: number;
  sort_by: BoardColumnSortMode;
  sort_direction: "asc" | "desc";
  is_default_for_leads: boolean;
  is_default_for_groups: boolean;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  /** Only meaningful when the parent conversation is_group=true: the
   *  contacts.id of the individual participant who sent this message
   *  inside the group (migration 049). NULL for 1:1 conversations and
   *  NULL when an inbound participant JID couldn't be resolved to a
   *  contact (e.g. a Baileys @lid identity). */
  sender_id?: string;
  /** Embedded contacts row for `sender_id`, when the fetch query joins
   *  it (message-thread.tsx does) — the group participant who sent
   *  this message. Undefined when the query didn't embed it; null when
   *  `sender_id` itself is null. */
  sender?: { id: string; name?: string; avatar_url?: string; phone: string } | null;
  /** Resolved @mentions for a group text message (migration 051) —
   *  `jid` is the raw Baileys JID/lid that was mentioned; `phone`/`name`
   *  are best-effort resolutions against the group's participant list
   *  (either can be null if the participant couldn't be resolved).
   *  Used to replace the raw `@<digits>` placeholder in `content_text`
   *  with a real name. Absent/null on every 1:1 message and on group
   *  messages that don't mention anyone. */
  mentions?: { jid: string; phone: string | null; name: string | null }[] | null;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

// ============================================================
// Inbox sidebar entities (migrations 038-042)
// ============================================================

export interface MessageFavorite {
  id: string;
  account_id: string;
  conversation_id: string;
  message_id: string;
  user_id: string;
  created_at: string;
}

export type ReminderStatus = 'pending' | 'completed';
/** 'manual' = created from the Inbox sidebar; 'automated' = created by an
 *  automation's "create_reminder" step (migration 046). */
export type ReminderSource = 'manual' | 'automated';

export interface ContactReminder {
  id: string;
  account_id: string;
  contact_id: string;
  conversation_id?: string;
  created_by_user_id: string;
  assigned_to_user_id?: string;
  title: string;
  due_at: string;
  completed_at?: string | null;
  source: ReminderSource;
  created_at: string;
}

export type AppointmentStatus = 'scheduled' | 'completed' | 'cancelled';

export interface ContactAppointment {
  id: string;
  account_id: string;
  contact_id: string;
  conversation_id?: string;
  created_by_user_id: string;
  assigned_to_user_id?: string;
  title: string;
  starts_at: string;
  ends_at?: string;
  location?: string;
  notes?: string;
  status: AppointmentStatus;
  created_at: string;
  updated_at: string;
}

export interface FaqEntry {
  id: string;
  account_id: string;
  question: string;
  answer: string;
  created_by_user_id?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `faq_entry_tags(tags(*))`. */
  tags?: Tag[];
}

export interface FaqEntryTag {
  id: string;
  faq_entry_id: string;
  tag_id: string;
  created_at: string;
}

// ============================================================
// Scheduled messages — "Mensagens agendadas" (migration 047)
// ============================================================

export type ScheduledMessageContentType = 'text' | 'image' | 'document' | 'audio' | 'video';
export type ScheduledMessageStatus = 'pending' | 'sent' | 'cancelled' | 'failed';

export interface ScheduledMessage {
  id: string;
  account_id: string;
  conversation_id: string;
  contact_id: string;
  created_by_user_id: string;
  content_type: ScheduledMessageContentType;
  content_text?: string | null;
  media_url?: string | null;
  filename?: string | null;
  reply_to_message_id?: string | null;
  scheduled_at: string;
  status: ScheduledMessageStatus;
  error_message?: string | null;
  sent_message_id?: string | null;
  created_at: string;
  updated_at: string;
  /** Hydrated by the "Mensagens agendadas" panel query. */
  conversation?: { id: string; contact?: { name?: string; phone: string } };
}

export type WhatsAppApiType = 'meta_cloud' | 'evolution';

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  account_id: string;
  /** Which provider this row talks to (migration 048). Meta-only fields
   *  below are optional because an 'evolution' row leaves them null —
   *  the DB CHECK (whatsapp_config_provider_fields_chk) enforces the
   *  right fields are present per api_type, not the TS type alone. */
  api_type: WhatsAppApiType;
  /** True if this is the provider used for 1:1 sends on this account.
   *  Group conversations always route to 'evolution' regardless of this
   *  flag — see resolveProviderConfig in
   *  src/lib/whatsapp/resolve-provider-config.ts. At most one row per
   *  account has is_primary=true (partial unique index). */
  is_primary: boolean;

  // ---- Meta Cloud API fields (api_type === 'meta_cloud') ----
  phone_number_id?: string;
  waba_id?: string;
  access_token?: string;
  verify_token?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;

  // ---- Evolution API fields (api_type === 'evolution') ----
  /** Evolution "instance" name — the session identifier in Evolution's
   *  own API, e.g. used in /instance/connect/{instanceName}. */
  instance_name?: string;
  /** Base URL of the self-hosted Evolution API server this row talks
   *  to. That server is infrastructure this app doesn't provision. */
  api_url?: string;
  /** Evolution's `apikey` header value — encrypted at rest with the
   *  same encrypt()/decrypt() as access_token. */
  api_key?: string;
  /** Random per-row secret checked (constant-time) on inbound webhook
   *  POSTs — Evolution has no HMAC-over-body scheme like Meta's. */
  webhook_secret?: string;

  status: 'connected' | 'disconnected';
  connected_at?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation'
  | 'create_reminder';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export interface CreateReminderStepConfig {
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation, same as
   *  UpdateContactFieldStepConfig.value. */
  title: string;
  due_in_amount: number;
  due_in_unit: 'minutes' | 'hours' | 'days';
  assign_to: 'author' | 'assigned_agent' | 'specific';
  /** Only used when assign_to === 'specific'. */
  assigned_to_user_id?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | CreateReminderStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Operações — Release A core (migrations 060-065)
//
// A flexible Folder → Board → Stage → Card module that sits
// alongside the legacy Pipeline/Deal model (Pipeline/PipelineStage/
// Deal above), not replacing it. See LEILAODESK_PRD_MESTRE.md.
// ============================================================

export interface OperationFolder {
  id: string;
  account_id: string;
  /** Max 1 level deep — enforced by a DB trigger, not just convention. */
  parent_folder_id: string | null;
  name: string;
  position: number;
  archived_at?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export interface OperationBoard {
  id: string;
  account_id: string;
  /** Nullable — a board may live at the account root without a folder. */
  folder_id: string | null;
  name: string;
  card_label_singular: string;
  card_label_plural: string;
  color: string;
  position: number;
  archived_at?: string | null;
  created_by?: string | null;
  /** The board's chosen date/datetime custom field, plotted on the Calendar view. */
  calendar_field_def_id?: string | null;
  /** Lets a board opt out of showing its Overview/Dashboard panel. */
  dashboard_hidden: boolean;
  created_at: string;
  updated_at: string;
}

export interface OperationBoardStage {
  id: string;
  board_id: string;
  name: string;
  color: string;
  /** Integer, renumbered in full on reorder — not fractional (few stages per board). */
  position: number;
  is_initial: boolean;
  /** Terminal stage (e.g. "Aprovado", "Descartado") — a board may have more than one. Drives the Dashboard's "cards concluídos" split. */
  is_final: boolean;
  archived_at?: string | null;
  created_at: string;
  updated_at: string;
}

export type OperationCardPriority = 'low' | 'normal' | 'high' | 'urgent';

export interface OperationCard {
  id: string;
  account_id: string;
  board_id: string;
  stage_id: string;
  title: string;
  description?: string | null;
  priority: OperationCardPriority;
  /** Fractional, partitioned per (board_id, stage_id) — reorder rewrites only the moved row. */
  position: number;
  assigned_to_user_id?: string | null;
  archived_at?: string | null;
  created_by?: string | null;
  /** Trigger-maintained from first-level tasks (parent_task_id IS NULL); null when the card has no first-level tasks yet. */
  progress_percent?: number | null;
  created_at: string;
  updated_at: string;
}

export type OperationCardFieldType =
  | 'short_text'
  | 'long_text'
  | 'number'
  | 'currency'
  | 'date'
  | 'datetime'
  | 'checkbox'
  | 'single_select'
  | 'multi_select'
  | 'phone'
  | 'email'
  | 'url'
  | 'user'
  | 'contact'
  | 'related_card';

export interface OperationCardFieldDef {
  id: string;
  board_id: string;
  /** Null = visible/required on every stage; set = only on that stage. */
  stage_id: string | null;
  name: string;
  field_type: OperationCardFieldType;
  field_options: Record<string, unknown>;
  is_required: boolean;
  position: number;
  archived_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface OperationCardFieldValue {
  id: string;
  card_id: string;
  field_def_id: string;
  value_text?: string | null;
  long_text?: string | null;
  value_number?: number | null;
  value_date?: string | null;
  value_boolean?: boolean | null;
  /** Polymorphic — auth.users.id / contacts.id / operation_cards.id depending on the field's type. */
  value_uuid?: string | null;
  value_multi_select?: string[] | null;
  created_at: string;
  updated_at: string;
}

export interface OperationCardTag {
  id: string;
  card_id: string;
  tag_id: string;
  created_at: string;
}

export interface OperationCardRelation {
  id: string;
  from_card_id: string;
  to_card_id: string;
  relation_type: string;
  created_by?: string | null;
  created_at: string;
}

export interface OperationCardContact {
  id: string;
  card_id: string;
  contact_id: string;
  relation_label?: string | null;
  created_at: string;
}

export interface OperationCardConversation {
  id: string;
  card_id: string;
  conversation_id: string;
  created_at: string;
}

export interface OperationCardComment {
  id: string;
  card_id: string;
  account_id: string;
  user_id?: string | null;
  comment_text: string;
  is_internal: boolean;
  /** Null = a general Card comment; set = scoped to that Task. */
  task_id?: string | null;
  created_at: string;
}

export interface OperationCardAttachment {
  id: string;
  card_id: string;
  account_id: string;
  uploaded_by_user_id?: string | null;
  storage_bucket: string;
  storage_path: string;
  file_name: string;
  mime_type?: string | null;
  size_bytes?: number | null;
  /** Null = a general Card attachment; set = scoped to that Task. */
  task_id?: string | null;
  created_at: string;
}

export type OperationCardActivityEventType =
  | 'card_created'
  | 'stage_changed'
  | 'assignee_changed'
  | 'priority_changed'
  | 'field_changed'
  | 'comment_added'
  | 'relation_added'
  | 'relation_removed'
  | 'attachment_added'
  | 'attachment_removed'
  | 'archived'
  | 'unarchived'
  | 'task_created'
  | 'task_completed'
  | 'task_reopened'
  | 'task_assignee_changed'
  | 'task_deleted'
  | 'checklist_item_toggled';

export interface OperationCardActivity {
  id: string;
  card_id: string;
  account_id: string;
  actor_user_id?: string | null;
  event_type: OperationCardActivityEventType;
  payload: Record<string, unknown>;
  created_at: string;
}

// ============================================================
// Operações — Release B (migrations 066-074)
//
// Tasks (optionally 1 level of subtasks), Checklists (Card- or
// Task-scoped), Task/Checklist Templates (global or board-specific,
// clone-on-apply), and configurable Dashboard indicators.
// ============================================================

export type OperationTaskStatus = 'todo' | 'in_progress' | 'done' | 'cancelled';

export interface OperationTask {
  id: string;
  card_id: string;
  account_id: string;
  /** Max 1 level deep — enforced by a DB trigger. */
  parent_task_id: string | null;
  title: string;
  description?: string | null;
  status: OperationTaskStatus;
  priority: OperationCardPriority;
  start_date?: string | null;
  due_at?: string | null;
  /** Free-text "group/section" label — no dedicated grouping table exists. */
  section?: string | null;
  assigned_to_user_id?: string | null;
  auto_complete_when_subtasks_done: boolean;
  completed_at?: string | null;
  completed_by_user_id?: string | null;
  /** Traceability only — never a live binding back to the template. */
  source_template_id?: string | null;
  /** Fractional, partitioned per (card_id, parent_task_id). */
  position: number;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export interface OperationChecklist {
  id: string;
  /** XOR with task_id — exactly one of the two is set. */
  card_id: string | null;
  task_id: string | null;
  title: string;
  position: number;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export interface OperationChecklistItem {
  id: string;
  checklist_id: string;
  item_text: string;
  is_done: boolean;
  note?: string | null;
  /** Fractional, partitioned per checklist_id. */
  position: number;
  created_at: string;
  updated_at: string;
}

export type OperationTaskTemplateAssigneeMode = 'none' | 'specific_user' | 'card_assignee';

export interface OperationTaskTemplate {
  id: string;
  account_id: string;
  /** Null = global to the account; set = specific to that board. */
  board_id: string | null;
  name: string;
  description?: string | null;
  default_priority: OperationCardPriority;
  default_assignee_mode: OperationTaskTemplateAssigneeMode;
  default_assignee_user_id?: string | null;
  default_due_offset_days?: number | null;
  default_section?: string | null;
  position: number;
  archived_at?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export interface OperationTaskTemplateSubtask {
  id: string;
  template_id: string;
  title: string;
  description?: string | null;
  default_priority: OperationCardPriority;
  default_due_offset_days?: number | null;
  position: number;
}

export interface OperationTaskTemplateChecklistItem {
  id: string;
  template_id: string;
  item_text: string;
  position: number;
}

export type OperationBoardIndicatorAggType = 'count' | 'sum' | 'avg' | 'min' | 'max' | 'percentage';

export interface OperationBoardIndicator {
  id: string;
  board_id: string;
  name: string;
  agg_type: OperationBoardIndicatorAggType;
  /** Required for sum/avg/min/max (must be a number/currency field); unused for count/percentage. */
  field_def_id?: string | null;
  /** Required for percentage (% of active cards in this stage); optional scope-narrower for count/sum/avg/min/max. */
  filter_stage_id?: string | null;
  position: number;
  archived_at?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

/** Return shape of the get_board_overview_stats RPC. */
export interface OperationBoardOverviewStats {
  active_cards: number;
  completed_cards: number;
  avg_progress: number | null;
  tasks_pending: number;
  tasks_overdue: number;
  tasks_due_today: number;
  tasks_due_this_week: number;
}
